# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Socket Lab - MTE - Swift/SocketServer

variables:
    repoName: 'tutorial-mte-socket-swift-macos'
    projDir: '$(repoName)/TutorialMTE'
    system_accesstoken: $(System.AccessToken)
    scheme: 'SocketServer'
    sdk: 'macosx'
    configuration: 'Debug'
    workspace: 'SocketServer.xcodeproj'

resources:
  repositories:
  - repository: mtelibs
    type: git
    name: Eclypses/package-swift-mte-macos
  - repository: mtewrapper
    type: git
    name: Eclypses/package-swift-mte-wrapper

pool: 'MTE-MacOS'

steps:

- checkout: self
  displayName: 'Checkout SocketServer'
  clean: true
  persistCredentials: true
- checkout: mtelibs
  displayName: 'Checkout Mte Library Files'
  clean: true
- checkout: mtewrapper
  displayName: 'Checkout Mte Wrapper Files'
  clean: true
    
- task: CopyFiles@2
  displayName: 'Copy MTE Library Files'
  inputs:
    SourceFolder: 'mte-libs/lib'
    Contents: '*.a'
    TargetFolder: '$(projDir)/MTE/lib'
    CleanTargetFolder: true
    OverWrite: true
    
- task: CopyFiles@2
  displayName: 'Copy MTE Header Files'
  inputs:
    SourceFolder: 'mte-libs/include'
    Contents: '**'
    TargetFolder: '$(projDir)/MTE/include'
    CleanTargetFolder: true
    OverWrite: true

- task: CopyFiles@2
  displayName: 'Copy MTE Wrapper Files'
  inputs:
    SourceFolder: 'package-swift-mte'
    Contents: 'Core/**' 
    TargetFolder: '$(projDir)/MTE'
    flattenFolders: true
    CleanTargetFolder: false
    OverWrite: true

- task: Xcode@5
  displayName: 'Build And Test SocketServer'
  inputs:
    actions: 'clean build test'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    xcWorkspacePath: '$(projDir)/SocketServer/$(workspace)'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'

- task: DeleteFiles@1
  displayName: 'Delete unnecessary files before push to public remote'
  inputs:
    SourceFolder: $(repoName)
    Contents: |
      .gitignore
      **/*.yml

- script: |
    git add .
    git commit -am 'Commit unnecessary file deletion'
  displayName: 'Commit unnecessary file deletion'
  workingDirectory: $(repoName)

- script: |
    git push https://nzkomtwqfr46wdlfw5omsj4olbn4zwhusarcpxpoux7zdoohltjq@dev.azure.com/eclypses/Private_Test/_git/tutorial-mte-socket-swift-macos HEAD:master --force
  displayName: 'Push to public repo'
  workingDirectory: $(repoName)
