# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

variables:
    projDir: 'lab-socket-macos-swift/Socket Lab - MTE - Swift'
    system_accesstoken: $(System.AccessToken)
    scheme: 'SocketServer'
    sdk: 'macosx'
    configuration: 'Debug'
    workspace: 'SocketServer.xcodeproj'

resources:
  repositories:
  - repository: mtelibs
    type: git
    name: Eclypses/mte-libs
  - repository: mtewrapper
    type: git
    name: Eclypses/package-swift-mte

pool: 'MTE-MacOS'

steps:

- checkout: self
  displayName: 'Checkout SocketServer'
  clean: true
  persistCredentials: true
- checkout: mtelibs
  displayName: 'Checkout Mte Library Files'
  clean: true
- checkout: mtewrapper
  displayName: 'Checkout Mte Wrapper Files'
  clean: true
    
- task: CopyFiles@2
  displayName: 'Copy MTE Library Files'
  inputs:
    SourceFolder: 'mte-libs/lib'
    Contents: '*.a'
    TargetFolder: '$(projDir)/MTE/lib'
    CleanTargetFolder: true
    OverWrite: true
    
- task: CopyFiles@2
  displayName: 'Copy MTE Header Files'
  inputs:
    SourceFolder: 'mte-libs/include'
    Contents: '**'
    TargetFolder: '$(projDir)/MTE/include'
    CleanTargetFolder: true
    OverWrite: true

- task: CopyFiles@2
  displayName: 'Copy MTE Wrapper Files'
  inputs:
    SourceFolder: 'package-swift-mte'
    Contents: 'Core/**' 
    TargetFolder: '$(projDir)/MTE'
    flattenFolders: true
    CleanTargetFolder: false
    OverWrite: true

- task: Xcode@5
  displayName: 'Build And Test SocketServer'
  inputs:
    actions: 'clean build test'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    xcWorkspacePath: '**/$(workspace)'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'

